# Image Enhancement
image_enhancement:
  gamma_correction:
    gamma: 1.5
  gaussian_smoothing:
    kernel_size: [5, 5] # (width, height)
    sigma_x: 1.0
    sigma_y: 1.0 # If different sigma for y is needed, else sigma_x is used for both
  hue_saturation_adjust:
    hue_shift_range: [-10, 10] # Shift in degrees
    saturation_scale_range: [-5, 5] # Scaler factor to multiply saturation (actual values might be 0.95 to 1.05)
                                    # Paper mentions -5 to +5, which is unusual for saturation directly.
                                    # This might refer to an additive change or specific library implementation.
                                    # For OpenCV, saturation is typically 0-255 or 0-1 in float.
                                    # Let's assume it means adjusting saturation by a small percentage.
                                    # Or it could be an absolute change in the S channel of HSV.

# Video Stabilization
video_stabilization:
  motion_estimation:
    max_corners: 100 # For Lucas-Kanade point tracking
    quality_level: 0.01
    min_distance: 10
    # Other LK parameters
  motion_smoothing:
    smoothing_radius: 15 # Number of frames for moving average filter
  # No specific parameters for motion compensation other than applying the smoothed transform

# Redundant Frame Removal
redundant_frame_removal:
  cosine_similarity_threshold: 0.90 # Remove frames with >= 90% similarity

# Canopy Segmentation (parameters for using the trained model)
# The model itself is defined in model.yaml and trained separately
canopy_segmentation:
  model_confidence_threshold: 0.5 # Confidence for segmenting the canopy
  # Other post-processing for masks if needed